### ISSUE TITLE
`docker-compose` commands to be updated to `docker compose`

### ISSUE THREAD

**Issue by kbennett2000** [agoric-labs/dapp-game-places#13]
The format of the docker compose command has changed.
- Old format: `docker-compose`
- New format: `docker compose`

Currently the package.json files in the demo and demo/contract folders still use the old format, and require the user to manually update both files.

**Comment by dckc** [comment]
Didn't I fix that already? Oh. Nope:

https://github.com/agoric-labs/dapp-game-places/blob/fc079d6ec8efc079f06a856b5e5ff49225d2d8cd/package.json#L17-L19

**Comment by dckc** [comment]
For ref:

> Version one of the Docker Compose command-line binary was first released in 2014. It was written in Python, and is invoked with docker-compose.
> Version two of the Docker Compose command-line binary was announced in 2020, is written in Go, and is invoked with docker compose. 

  -- [History and development of Docker Compose](https://docs.docker.com/compose/history/)
